# Generated by Django 5.0.1 on 2024-02-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
    ]
